---
name: ditonton
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.1.3
  flutter_bloc: ^8.0.0
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.6.0
  about:
    path: about
  core:
    path: core
  search:
    path: search

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0
  mockito: ^5.0.8


flutter:
  uses-material-design: true
  assets:
  - assets/
  - certificates/
