library core;

export 'package:core/styles/colors.dart';
export 'package:core/styles/text_styles.dart';

// data
export 'data/datasources/db/database_helper.dart';
export 'data/datasources/movie/movie_local_data_source.dart';
export 'data/datasources/movie/movie_remote_data_source.dart';
export 'data/datasources/tvshow/tvshow_local_data_source.dart';
export 'data/datasources/tvshow/tvshow_remote_data_source.dart';
export 'data/models/genre_model.dart';
export 'data/models/movie_detail_model.dart';
export 'data/models/movie_model.dart';
export 'data/models/movie_response.dart';
export 'data/models/movie_table.dart';
export 'data/models/tvshow/lastepisode/lastepisode.dart';
export 'data/models/tvshow/season/season.dart';
export 'data/models/tvshow/tv_detail_model.dart';
export 'data/models/tvshow/tv_model.dart';
export 'data/models/tvshow/tv_response.dart';
export 'data/models/tvshow/tv_table.dart';
export 'data/repositories/movie_repository_impl.dart';
export 'data/repositories/tvshow_repository_impl.dart';
export 'domain/entities/genre.dart';
export 'domain/entities/movie.dart';
export 'domain/entities/movie_detail.dart';
export 'domain/entities/tvshow/lastepisode.dart';
export 'domain/entities/tvshow/tvshow.dart';
export 'domain/entities/tvshow/tvshow_detail.dart';
export 'domain/repositories/movie_repository.dart';
export 'domain/repositories/tvshow_repository.dart';
// domain
export 'domain/usecases/get_movie_detail.dart';
export 'domain/usecases/get_movie_recommendations.dart';
export 'domain/usecases/get_now_playing_movies.dart';
export 'domain/usecases/get_popular_movies.dart';
export 'domain/usecases/get_top_rated_movies.dart';
export 'domain/usecases/get_watchlist_movies.dart';
export 'domain/usecases/get_watchlist_status.dart';
export 'domain/usecases/remove_watchlist.dart';
export 'domain/usecases/save_watchlist.dart';
export 'domain/usecases/tvshow/get_popular_tvshow.dart';
export 'domain/usecases/tvshow/get_top_rated_tvshow.dart';
export 'domain/usecases/tvshow/get_tvshow_detail.dart';
export 'domain/usecases/tvshow/get_tvshow_on_the_air.dart';
export 'domain/usecases/tvshow/get_tvshow_recommendations.dart';
export 'domain/usecases/tvshow/get_watchlist_tvshow.dart';
export 'domain/usecases/tvshow/get_watchlist_tvshow_status.dart';
export 'domain/usecases/tvshow/remove_watchlist_tvshow.dart';
export 'domain/usecases/tvshow/save_watchlist_tvshow.dart';
//bloc
export 'presentation/bloc/movies/detail/detail_movie_bloc.dart';
export 'presentation/bloc/movies/detail/watchlist/detail_watchlist_movie_bloc.dart';
export 'presentation/bloc/movies/now_playing/now_playing_bloc.dart';
export 'presentation/bloc/movies/popular/popular_movies_bloc.dart';
export 'presentation/bloc/movies/top_rated/top_rated_movies_bloc.dart';
export 'presentation/bloc/movies/watchlist/watchlist_movies_bloc.dart';
export 'presentation/bloc/tvshow/airing/on_the_air_tv_show_bloc.dart';
export 'presentation/bloc/tvshow/detail/detail_tv_show_bloc.dart';
export 'presentation/bloc/tvshow/detail/watchlist/detail_watchlist_bloc.dart';
export 'presentation/bloc/tvshow/popular/popular_tv_show_bloc.dart';
export 'presentation/bloc/tvshow/top_rated/top_rated_tv_show_bloc.dart';
export 'presentation/bloc/tvshow/watchlist/watchlist_tv_show_bloc.dart';
//pages
export 'presentation/pages/home_page.dart';
export 'presentation/pages/movie_detail_page.dart';
export 'presentation/pages/on_the_air_tvshows_page.dart';
export 'presentation/pages/popular_movies_page.dart';
export 'presentation/pages/popular_tvshows_page.dart';
export 'presentation/pages/top_rated_movies_page.dart';
export 'presentation/pages/top_rated_tvshows_page.dart';
export 'presentation/pages/tvshow_detail_page.dart';
export 'presentation/pages/tvshow_page.dart';
export 'presentation/pages/watchlist_page.dart';
//widgets
export 'presentation/widgets/custom_subheading_list.dart';
export 'presentation/widgets/movie_card_list.dart';
export 'presentation/widgets/tvshow_card_list.dart';
//utils
export 'utils/constants.dart';
export 'utils/exception.dart';
export 'utils/failure.dart';
export 'utils/state_enum.dart';
export 'utils/utils.dart';
